from PyQt5.QtCore import *
from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
import matplotlib.pyplot as plt
import cv2 as cv
from PyQt5.QtGui import QIntValidator
import datetime
from datetime import datetime, timedelta
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QMainWindow, QApplication, QGraphicsScene, QGraphicsPixmapItem,QFileDialog,QDialog,QApplication
from PyQt5 import QtCore, QtGui, QtWidgets
now_output_time = str(datetime.now().strftime('%Y-%m-%d %H-%M-%S'))
import os
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

#曲線顏色
colorTab_More4 = ['#e8a5eb', '#facc9e', '#e8e948', '#1bb763',
                       '#25f2f3', '#1db3ea', '#d1aef8', '#c8c92c',
                       '#f32020', '#fd9b09', '#406386', '#24a1a1',
                       '#1515f8', '#959697', '#744a20', '#7b45a5']

class Ui_MainWindow(QtWidgets.QWidget):
    def browsefile(self):
        if not os.path.isdir('./result'):
            print("Directory 'result' does not exist.")
            os.mkdir('./result')
        print(now_output_time +" >> Choose file(csv) ....")
        self.fname = QFileDialog.getOpenFileName(self, '開啟csv檔案', 'C:\Program Files (x86)', 'csv files (*.csv)')
        self.file_csv_input.setText(self.fname[0])
        print(now_output_time +" >> Open File: " + str(self.fname[0]))
    
    def calculate(self):
        self.big_well = []
        self.big_data = []
        # if self.baseline_start_time.text() == "" or self.baseline_end_time.text() == "":
        # print("yes")


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 783)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Threshold = QtWidgets.QGroupBox(self.centralwidget)
        self.Threshold.setGeometry(QtCore.QRect(10, 354, 931, 403))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Threshold.setFont(font)
        self.Threshold.setStyleSheet("border-color: rgb(85, 255, 255);")
        self.Threshold.setObjectName("Threshold")
        self.Threshold_function = QtWidgets.QGroupBox(self.Threshold)
        self.Threshold_function.setGeometry(QtCore.QRect(20, 96, 341, 301))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Threshold_function.setFont(font)
        self.Threshold_function.setObjectName("Threshold_function")
        self.Baseline = QtWidgets.QGroupBox(self.Threshold_function)
        self.Baseline.setGeometry(QtCore.QRect(10, 174, 321, 67))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Baseline.setFont(font)
        self.Baseline.setObjectName("Baseline")
        self.layoutWidget = QtWidgets.QWidget(self.Baseline)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 25, 301, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.baseline = QtWidgets.QGridLayout(self.layoutWidget)
        self.baseline.setContentsMargins(0, 0, 0, 0)
        self.baseline.setObjectName("baseline")
        self.baseline_start = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.baseline_start.setFont(font)
        self.baseline_start.setAlignment(QtCore.Qt.AlignCenter)
        self.baseline_start.setObjectName("baseline_start")
        self.baseline.addWidget(self.baseline_start, 0, 0, 1, 1)
        self.baseline_start_time = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.baseline_start_time.setFont(font)
        self.baseline_start_time.setAlignment(QtCore.Qt.AlignCenter)
        self.baseline_start_time.setObjectName("baseline_start_time")
        self.baseline.addWidget(self.baseline_start_time, 0, 1, 1, 1)
        self.baseline_end = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.baseline_end.setFont(font)
        self.baseline_end.setAlignment(QtCore.Qt.AlignCenter)
        self.baseline_end.setObjectName("baseline_end")
        self.baseline.addWidget(self.baseline_end, 0, 2, 1, 1)
        self.baseline_end_time = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.baseline_end_time.setFont(font)
        self.baseline_end_time.setAlignment(QtCore.Qt.AlignCenter)
        self.baseline_end_time.setObjectName("baseline_end_time")
        self.baseline.addWidget(self.baseline_end_time, 0, 3, 1, 1)
        self.update_calculation = QtWidgets.QPushButton(self.Threshold_function)
        self.update_calculation.setGeometry(QtCore.QRect(140, 252, 191, 37))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.update_calculation.setFont(font)
        self.update_calculation.setObjectName("update_calculation")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Threshold)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(380, 108, 311, 289))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.result_grip = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.result_grip.setContentsMargins(0, 0, 0, 0)
        self.result_grip.setObjectName("result_grip")
        self.result_value = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.result_value.setFont(font)
        self.result_value.setObjectName("result_value")
        self.result_value.setColumnCount(2)
        self.result_value.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.result_value.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setItem(0, 1, item)
        self.result_grip.addWidget(self.result_value, 0, 0, 1, 1)
        self.File = QtWidgets.QGroupBox(self.Threshold)
        self.File.setGeometry(QtCore.QRect(20, 24, 901, 67))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.File.setFont(font)
        self.File.setObjectName("File")
        self.file_csv = QtWidgets.QLabel(self.File)
        self.file_csv.setGeometry(QtCore.QRect(10, 30, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.file_csv.setFont(font)
        self.file_csv.setAlignment(QtCore.Qt.AlignCenter)
        self.file_csv.setObjectName("file_csv")
        self.file_csv_input = QtWidgets.QLineEdit(self.File)
        self.file_csv_input.setGeometry(QtCore.QRect(90, 24, 621, 37))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.file_csv_input.setFont(font)
        self.file_csv_input.setObjectName("file_csv_input")
        self.file_open = QtWidgets.QPushButton(self.File)
        self.file_open.setGeometry(QtCore.QRect(720, 24, 171, 37))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.file_open.setFont(font)
        self.file_open.setObjectName("file_open")
        self.layoutWidget1 = QtWidgets.QWidget(self.Threshold)
        self.layoutWidget1.setGeometry(QtCore.QRect(740, 108, 181, 115))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_save = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("color: rgb(0, 170, 0);")
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout.addWidget(self.btn_save)
        self.btn_capture = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_capture.setFont(font)
        self.btn_capture.setObjectName("btn_capture")
        self.verticalLayout.addWidget(self.btn_capture)
        self.btn_clear = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("color: rgb(255, 0, 0);")
        self.btn_clear.setObjectName("btn_clear")
        self.verticalLayout.addWidget(self.btn_clear)
        self.Sample = QtWidgets.QGroupBox(self.centralwidget)
        self.Sample.setGeometry(QtCore.QRect(800, 6, 141, 343))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Sample.setFont(font)
        self.Sample.setObjectName("Sample")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Sample)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_A = QtWidgets.QVBoxLayout()
        self.verticalLayout_A.setObjectName("verticalLayout_A")
        self.CT_A1 = QtWidgets.QCheckBox(self.Sample)
        self.CT_A1.setObjectName("CT_A1")
        self.verticalLayout_A.addWidget(self.CT_A1)
        self.CT_A2 = QtWidgets.QCheckBox(self.Sample)
        self.CT_A2.setObjectName("CT_A2")
        self.verticalLayout_A.addWidget(self.CT_A2)
        self.CT_A3 = QtWidgets.QCheckBox(self.Sample)
        self.CT_A3.setObjectName("CT_A3")
        self.verticalLayout_A.addWidget(self.CT_A3)
        self.CT_A4 = QtWidgets.QCheckBox(self.Sample)
        self.CT_A4.setObjectName("CT_A4")
        self.verticalLayout_A.addWidget(self.CT_A4)
        self.CT_A5 = QtWidgets.QCheckBox(self.Sample)
        self.CT_A5.setObjectName("CT_A5")
        self.verticalLayout_A.addWidget(self.CT_A5)
        self.CT_A6 = QtWidgets.QCheckBox(self.Sample)
        self.CT_A6.setObjectName("CT_A6")
        self.verticalLayout_A.addWidget(self.CT_A6)
        self.CT_A7 = QtWidgets.QCheckBox(self.Sample)
        self.CT_A7.setObjectName("CT_A7")
        self.verticalLayout_A.addWidget(self.CT_A7)
        self.CT_A8 = QtWidgets.QCheckBox(self.Sample)
        self.CT_A8.setObjectName("CT_A8")
        self.verticalLayout_A.addWidget(self.CT_A8)
        self.gridLayout.addLayout(self.verticalLayout_A, 0, 0, 1, 1)
        self.verticalLayout_B = QtWidgets.QVBoxLayout()
        self.verticalLayout_B.setObjectName("verticalLayout_B")
        self.CT_B1 = QtWidgets.QCheckBox(self.Sample)
        self.CT_B1.setObjectName("CT_B1")
        self.verticalLayout_B.addWidget(self.CT_B1)
        self.CT_B2 = QtWidgets.QCheckBox(self.Sample)
        self.CT_B2.setObjectName("CT_B2")
        self.verticalLayout_B.addWidget(self.CT_B2)
        self.CT_B3 = QtWidgets.QCheckBox(self.Sample)
        self.CT_B3.setObjectName("CT_B3")
        self.verticalLayout_B.addWidget(self.CT_B3)
        self.CT_B4 = QtWidgets.QCheckBox(self.Sample)
        self.CT_B4.setObjectName("CT_B4")
        self.verticalLayout_B.addWidget(self.CT_B4)
        self.CT_B5 = QtWidgets.QCheckBox(self.Sample)
        self.CT_B5.setObjectName("CT_B5")
        self.verticalLayout_B.addWidget(self.CT_B5)
        self.CT_B6 = QtWidgets.QCheckBox(self.Sample)
        self.CT_B6.setObjectName("CT_B6")
        self.verticalLayout_B.addWidget(self.CT_B6)
        self.CT_B7 = QtWidgets.QCheckBox(self.Sample)
        self.CT_B7.setObjectName("CT_B7")
        self.verticalLayout_B.addWidget(self.CT_B7)
        self.CT_B8 = QtWidgets.QCheckBox(self.Sample)
        self.CT_B8.setObjectName("CT_B8")
        self.verticalLayout_B.addWidget(self.CT_B8)
        self.gridLayout.addLayout(self.verticalLayout_B, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.version = QtWidgets.QLabel(self.centralwidget)
        self.version.setGeometry(QtCore.QRect(10, 762, 301, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.version.setFont(font)
        self.version.setObjectName("version")
        self.Plot = QtWidgets.QGroupBox(self.centralwidget)
        self.Plot.setGeometry(QtCore.QRect(10, 7, 781, 343))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Plot.setFont(font)
        self.Plot.setObjectName("Plot")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Plot)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Plot_display = QtWidgets.QGraphicsView(self.Plot)
        self.Plot_display.setObjectName("Plot_display")
        self.gridLayout_2.addWidget(self.Plot_display, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #執行功能
        self.file_open.clicked.connect(self.browsefile)
        self.update_calculation.clicked.connect(self.calculate)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Amplification Plot"))
        self.Threshold.setTitle(_translate("MainWindow", "Threshold"))
        self.Threshold_function.setTitle(_translate("MainWindow", "Threshold"))
        self.Baseline.setTitle(_translate("MainWindow", "Baseline(Min)"))
        self.baseline_start.setText(_translate("MainWindow", "Start:"))
        self.baseline_end.setText(_translate("MainWindow", "End:"))
        self.update_calculation.setText(_translate("MainWindow", "Update Calculations"))
        item = self.result_value.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "A1"))
        item = self.result_value.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "A2"))
        item = self.result_value.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "A3"))
        item = self.result_value.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "A4"))
        item = self.result_value.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "A5"))
        item = self.result_value.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "A6"))
        item = self.result_value.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "A7"))
        item = self.result_value.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "A8"))
        item = self.result_value.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "B1"))
        item = self.result_value.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "B2"))
        item = self.result_value.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "B3"))
        item = self.result_value.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "B4"))
        item = self.result_value.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "B5"))
        item = self.result_value.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "B6"))
        item = self.result_value.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "B7"))
        item = self.result_value.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "B8"))
        item = self.result_value.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ct Value"))
        item = self.result_value.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Std Dev"))
        __sortingEnabled = self.result_value.isSortingEnabled()
        self.result_value.setSortingEnabled(False)
        self.result_value.setSortingEnabled(__sortingEnabled)
        self.File.setTitle(_translate("MainWindow", "File(Csv)"))
        self.file_csv.setText(_translate("MainWindow", "Dir:"))
        self.file_open.setText(_translate("MainWindow", "Open(Csv)"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
        self.btn_capture.setText(_translate("MainWindow", "Capture"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.Sample.setTitle(_translate("MainWindow", "Samples"))
        self.CT_A1.setText(_translate("MainWindow", "A1"))
        self.CT_A2.setText(_translate("MainWindow", "A2"))
        self.CT_A3.setText(_translate("MainWindow", "A3"))
        self.CT_A4.setText(_translate("MainWindow", "A4"))
        self.CT_A5.setText(_translate("MainWindow", "A5"))
        self.CT_A6.setText(_translate("MainWindow", "A6"))
        self.CT_A7.setText(_translate("MainWindow", "A7"))
        self.CT_A8.setText(_translate("MainWindow", "A8"))
        self.CT_B1.setText(_translate("MainWindow", "B1"))
        self.CT_B2.setText(_translate("MainWindow", "B2"))
        self.CT_B3.setText(_translate("MainWindow", "B3"))
        self.CT_B4.setText(_translate("MainWindow", "B4"))
        self.CT_B5.setText(_translate("MainWindow", "B5"))
        self.CT_B6.setText(_translate("MainWindow", "B6"))
        self.CT_B7.setText(_translate("MainWindow", "B7"))
        self.CT_B8.setText(_translate("MainWindow", "B8"))
        self.version.setText(_translate("MainWindow", "WinnoZ. V. 1.0.2"))
        self.Plot.setTitle(_translate("MainWindow", "Plot"))
if __name__ == '__main__':
    print("*" * 50)
    print("Now Time: " + now_output_time)
    print("*" * 50)
    app = QApplication(sys.argv)
    mainWindows = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindows)
    mainWindows.show()
    sys.exit(app.exec_())