import sys
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtChart import QChartView
from PyQt5 import QtCore, QtGui, QtWidgets

#Ui介面設置
class Ui_MainWindow(object):
    def showtime(self):
        time=QDateTime.currentDateTime()#獲取當前時間
        timedisplay=time.toString("yyyy-MM-dd hh:mm:ss")#格式化一下時間
        # print(timedisplay)
        self.label_time.setText(timedisplay)
    
    def starttimer(self):
        self.timer.start(1000)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(956, 493)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plot_view = QChartView(self.centralwidget)
        self.plot_view.setGeometry(QtCore.QRect(10, 12, 741, 349))
        self.plot_view.setObjectName("plot_view")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(730, 426, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_time.setFont(font)
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(760, 12, 171, 403))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_A1 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_A1.setFont(font)
        self.checkBox_A1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_A1.setStyleSheet("gridline-color: rgb(0, 0, 0);")
        self.checkBox_A1.setObjectName("checkBox_A1")
        self.gridLayout.addWidget(self.checkBox_A1, 0, 0, 1, 1)
        self.checkBox_B2 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_B2.setFont(font)
        self.checkBox_B2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_B2.setObjectName("checkBox_B2")
        self.gridLayout.addWidget(self.checkBox_B2, 1, 1, 1, 1)
        self.checkBox_B1 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_B1.setFont(font)
        self.checkBox_B1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_B1.setObjectName("checkBox_B1")
        self.gridLayout.addWidget(self.checkBox_B1, 0, 1, 1, 1)
        self.checkBox_A3 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_A3.setFont(font)
        self.checkBox_A3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_A3.setObjectName("checkBox_A3")
        self.gridLayout.addWidget(self.checkBox_A3, 2, 0, 1, 1)
        self.checkBox_B3 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_B3.setFont(font)
        self.checkBox_B3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_B3.setObjectName("checkBox_B3")
        self.gridLayout.addWidget(self.checkBox_B3, 2, 1, 1, 1)
        self.checkBox_A4 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_A4.setFont(font)
        self.checkBox_A4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_A4.setObjectName("checkBox_A4")
        self.gridLayout.addWidget(self.checkBox_A4, 3, 0, 1, 1)
        self.checkBox_A6 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_A6.setFont(font)
        self.checkBox_A6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_A6.setObjectName("checkBox_A6")
        self.gridLayout.addWidget(self.checkBox_A6, 5, 0, 1, 1)
        self.checkBox_B7 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_B7.setFont(font)
        self.checkBox_B7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_B7.setObjectName("checkBox_B7")
        self.gridLayout.addWidget(self.checkBox_B7, 6, 1, 1, 1)
        self.checkBox_B6 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_B6.setFont(font)
        self.checkBox_B6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_B6.setObjectName("checkBox_B6")
        self.gridLayout.addWidget(self.checkBox_B6, 5, 1, 1, 1)
        self.checkBox_A2 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_A2.setFont(font)
        self.checkBox_A2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_A2.setObjectName("checkBox_A2")
        self.gridLayout.addWidget(self.checkBox_A2, 1, 0, 1, 1)
        self.checkBox_B5 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_B5.setFont(font)
        self.checkBox_B5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_B5.setObjectName("checkBox_B5")
        self.gridLayout.addWidget(self.checkBox_B5, 4, 1, 1, 1)
        self.checkBox_A7 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_A7.setFont(font)
        self.checkBox_A7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_A7.setObjectName("checkBox_A7")
        self.gridLayout.addWidget(self.checkBox_A7, 6, 0, 1, 1)
        self.checkBox_A5 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_A5.setFont(font)
        self.checkBox_A5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_A5.setObjectName("checkBox_A5")
        self.gridLayout.addWidget(self.checkBox_A5, 4, 0, 1, 1)
        self.checkBox_B8 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_B8.setFont(font)
        self.checkBox_B8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_B8.setObjectName("checkBox_B8")
        self.gridLayout.addWidget(self.checkBox_B8, 7, 1, 1, 1)
        self.checkBox_B4 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_B4.setFont(font)
        self.checkBox_B4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_B4.setObjectName("checkBox_B4")
        self.gridLayout.addWidget(self.checkBox_B4, 3, 1, 1, 1)
        self.checkBox_A8 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_A8.setFont(font)
        self.checkBox_A8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_A8.setObjectName("checkBox_A8")
        self.gridLayout.addWidget(self.checkBox_A8, 7, 0, 1, 1)
        self.checkBox_all = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_all.setFont(font)
        self.checkBox_all.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_all.setObjectName("checkBox_all")
        self.gridLayout.addWidget(self.checkBox_all, 8, 0, 1, 1)
        self.checkBox_clear = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_clear.setFont(font)
        self.checkBox_clear.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_clear.setObjectName("checkBox_clear")
        self.gridLayout.addWidget(self.checkBox_clear, 8, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 372, 741, 43))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_resetfile = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_resetfile.setFont(font)
        self.btn_resetfile.setStyleSheet("color: rgb(255, 255, 0);\n"
"color: rgb(206, 206, 0);")
        self.btn_resetfile.setObjectName("btn_resetfile")
        self.gridLayout_3.addWidget(self.btn_resetfile, 0, 2, 1, 1)
        self.btn_clean = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clean.setFont(font)
        self.btn_clean.setStyleSheet("color: rgb(255, 0, 0);")
        self.btn_clean.setObjectName("btn_clean")
        self.gridLayout_3.addWidget(self.btn_clean, 0, 3, 1, 1)
        self.btn_savefile = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_savefile.setFont(font)
        self.btn_savefile.setStyleSheet("color: rgb(74, 221, 0);")
        self.btn_savefile.setObjectName("btn_savefile")
        self.gridLayout_3.addWidget(self.btn_savefile, 0, 1, 1, 1)
        self.btn_openfile = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_openfile.setFont(font)
        self.btn_openfile.setStyleSheet("color: rgb(85, 0, 255);")
        self.btn_openfile.setObjectName("btn_openfile")
        self.gridLayout_3.addWidget(self.btn_openfile, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 956, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuUser = QtWidgets.QMenu(self.menubar)
        self.menuUser.setObjectName("menuUser")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuWindows = QtWidgets.QMenu(self.menubar)
        self.menuWindows.setObjectName("menuWindows")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.actionNew.setFont(font)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionOptions)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuUser.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.timer = QTimer()
        self.timer.timeout.connect(self.showtime)
        self.starttimer()
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_time.setText(_translate("MainWindow", "時間日期"))
        self.checkBox_A1.setText(_translate("MainWindow", "A1"))
        self.checkBox_B2.setText(_translate("MainWindow", "B2"))
        self.checkBox_B1.setText(_translate("MainWindow", "B1"))
        self.checkBox_A3.setText(_translate("MainWindow", "A3"))
        self.checkBox_B3.setText(_translate("MainWindow", "B3"))
        self.checkBox_A4.setText(_translate("MainWindow", "A4"))
        self.checkBox_A6.setText(_translate("MainWindow", "A6"))
        self.checkBox_B7.setText(_translate("MainWindow", "B7"))
        self.checkBox_B6.setText(_translate("MainWindow", "B6"))
        self.checkBox_A2.setText(_translate("MainWindow", "A2"))
        self.checkBox_B5.setText(_translate("MainWindow", "B5"))
        self.checkBox_A7.setText(_translate("MainWindow", "A7"))
        self.checkBox_A5.setText(_translate("MainWindow", "A5"))
        self.checkBox_B8.setText(_translate("MainWindow", "B8"))
        self.checkBox_B4.setText(_translate("MainWindow", "B4"))
        self.checkBox_A8.setText(_translate("MainWindow", "A8"))
        self.checkBox_all.setText(_translate("MainWindow", "All"))
        self.checkBox_clear.setText(_translate("MainWindow", "Clear"))
        self.btn_resetfile.setText(_translate("MainWindow", "Reset"))
        self.btn_clean.setText(_translate("MainWindow", "Clean"))
        self.btn_savefile.setText(_translate("MainWindow", "Save"))
        self.btn_openfile.setText(_translate("MainWindow", "Open"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuUser.setTitle(_translate("MainWindow", "User"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuWindows.setTitle(_translate("MainWindow", "Windows"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))


