# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AmplificationPlot.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 792)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 354, 931, 403))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("border-color: rgb(85, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.Threshold = QtWidgets.QGroupBox(self.groupBox)
        self.Threshold.setGeometry(QtCore.QRect(20, 102, 341, 265))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Threshold.setFont(font)
        self.Threshold.setObjectName("Threshold")
        self.Baseline = QtWidgets.QGroupBox(self.Threshold)
        self.Baseline.setGeometry(QtCore.QRect(10, 144, 321, 67))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Baseline.setFont(font)
        self.Baseline.setObjectName("Baseline")
        self.widget = QtWidgets.QWidget(self.Baseline)
        self.widget.setGeometry(QtCore.QRect(10, 25, 301, 31))
        self.widget.setObjectName("widget")
        self.baseline = QtWidgets.QGridLayout(self.widget)
        self.baseline.setContentsMargins(0, 0, 0, 0)
        self.baseline.setObjectName("baseline")
        self.baseline_start = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.baseline_start.setFont(font)
        self.baseline_start.setAlignment(QtCore.Qt.AlignCenter)
        self.baseline_start.setObjectName("baseline_start")
        self.baseline.addWidget(self.baseline_start, 0, 0, 1, 1)
        self.baseline_start_time = QtWidgets.QLineEdit(self.widget)
        self.baseline_start_time.setAlignment(QtCore.Qt.AlignCenter)
        self.baseline_start_time.setObjectName("baseline_start_time")
        self.baseline.addWidget(self.baseline_start_time, 0, 1, 1, 1)
        self.baseline_end = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.baseline_end.setFont(font)
        self.baseline_end.setAlignment(QtCore.Qt.AlignCenter)
        self.baseline_end.setObjectName("baseline_end")
        self.baseline.addWidget(self.baseline_end, 0, 2, 1, 1)
        self.baseline_end_time = QtWidgets.QLineEdit(self.widget)
        self.baseline_end_time.setAlignment(QtCore.Qt.AlignCenter)
        self.baseline_end_time.setObjectName("baseline_end_time")
        self.baseline.addWidget(self.baseline_end_time, 0, 3, 1, 1)
        self.update_calculation = QtWidgets.QPushButton(self.Threshold)
        self.update_calculation.setGeometry(QtCore.QRect(140, 222, 191, 37))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.update_calculation.setFont(font)
        self.update_calculation.setObjectName("update_calculation")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(380, 108, 301, 259))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.result_grip = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.result_grip.setContentsMargins(0, 0, 0, 0)
        self.result_grip.setObjectName("result_grip")
        self.result_value = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.result_value.setFont(font)
        self.result_value.setObjectName("result_value")
        self.result_value.setColumnCount(2)
        self.result_value.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.result_value.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.result_value.setItem(0, 1, item)
        self.result_grip.addWidget(self.result_value, 0, 0, 1, 1)
        self.File = QtWidgets.QGroupBox(self.groupBox)
        self.File.setGeometry(QtCore.QRect(20, 24, 901, 67))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.File.setFont(font)
        self.File.setObjectName("File")
        self.file_csv = QtWidgets.QLabel(self.File)
        self.file_csv.setGeometry(QtCore.QRect(10, 30, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.file_csv.setFont(font)
        self.file_csv.setAlignment(QtCore.Qt.AlignCenter)
        self.file_csv.setObjectName("file_csv")
        self.file_csv_input = QtWidgets.QLineEdit(self.File)
        self.file_csv_input.setGeometry(QtCore.QRect(90, 24, 621, 37))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.file_csv_input.setFont(font)
        self.file_csv_input.setObjectName("file_csv_input")
        self.update_calculation_2 = QtWidgets.QPushButton(self.File)
        self.update_calculation_2.setGeometry(QtCore.QRect(720, 24, 171, 37))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_calculation_2.setFont(font)
        self.update_calculation_2.setObjectName("update_calculation_2")
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(740, 108, 171, 97))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.update_calculation_3 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_calculation_3.setFont(font)
        self.update_calculation_3.setStyleSheet("color: rgb(0, 170, 0);")
        self.update_calculation_3.setObjectName("update_calculation_3")
        self.verticalLayout.addWidget(self.update_calculation_3)
        self.update_calculation_5 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_calculation_5.setFont(font)
        self.update_calculation_5.setObjectName("update_calculation_5")
        self.verticalLayout.addWidget(self.update_calculation_5)
        self.update_calculation_4 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_calculation_4.setFont(font)
        self.update_calculation_4.setStyleSheet("color: rgb(255, 0, 0);")
        self.update_calculation_4.setObjectName("update_calculation_4")
        self.verticalLayout.addWidget(self.update_calculation_4)
        self.Sample = QtWidgets.QGroupBox(self.centralwidget)
        self.Sample.setGeometry(QtCore.QRect(800, 12, 131, 337))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Sample.setFont(font)
        self.Sample.setObjectName("Sample")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Sample)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_A = QtWidgets.QVBoxLayout()
        self.verticalLayout_A.setObjectName("verticalLayout_A")
        self.checkBox_A1 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_A1.setObjectName("checkBox_A1")
        self.verticalLayout_A.addWidget(self.checkBox_A1)
        self.checkBox_A2 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_A2.setObjectName("checkBox_A2")
        self.verticalLayout_A.addWidget(self.checkBox_A2)
        self.checkBox_A3 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_A3.setObjectName("checkBox_A3")
        self.verticalLayout_A.addWidget(self.checkBox_A3)
        self.checkBox_A4 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_A4.setObjectName("checkBox_A4")
        self.verticalLayout_A.addWidget(self.checkBox_A4)
        self.checkBox_A5 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_A5.setObjectName("checkBox_A5")
        self.verticalLayout_A.addWidget(self.checkBox_A5)
        self.checkBox_A6 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_A6.setObjectName("checkBox_A6")
        self.verticalLayout_A.addWidget(self.checkBox_A6)
        self.checkBox_A7 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_A7.setObjectName("checkBox_A7")
        self.verticalLayout_A.addWidget(self.checkBox_A7)
        self.checkBox_A8 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_A8.setObjectName("checkBox_A8")
        self.verticalLayout_A.addWidget(self.checkBox_A8)
        self.gridLayout.addLayout(self.verticalLayout_A, 0, 0, 1, 1)
        self.verticalLayout_B = QtWidgets.QVBoxLayout()
        self.verticalLayout_B.setObjectName("verticalLayout_B")
        self.checkBox_B1 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_B1.setObjectName("checkBox_B1")
        self.verticalLayout_B.addWidget(self.checkBox_B1)
        self.checkBox_B2 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_B2.setObjectName("checkBox_B2")
        self.verticalLayout_B.addWidget(self.checkBox_B2)
        self.checkBox_B3 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_B3.setObjectName("checkBox_B3")
        self.verticalLayout_B.addWidget(self.checkBox_B3)
        self.checkBox_B4 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_B4.setObjectName("checkBox_B4")
        self.verticalLayout_B.addWidget(self.checkBox_B4)
        self.checkBox_B5 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_B5.setObjectName("checkBox_B5")
        self.verticalLayout_B.addWidget(self.checkBox_B5)
        self.checkBox_B6 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_B6.setObjectName("checkBox_B6")
        self.verticalLayout_B.addWidget(self.checkBox_B6)
        self.checkBox_B7 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_B7.setObjectName("checkBox_B7")
        self.verticalLayout_B.addWidget(self.checkBox_B7)
        self.checkBox_B8 = QtWidgets.QCheckBox(self.Sample)
        self.checkBox_B8.setObjectName("checkBox_B8")
        self.verticalLayout_B.addWidget(self.checkBox_B8)
        self.gridLayout.addLayout(self.verticalLayout_B, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 762, 301, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 18, 781, 331))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Amplification Plot"))
        self.groupBox.setTitle(_translate("MainWindow", "Threshold"))
        self.Threshold.setTitle(_translate("MainWindow", "Threshold"))
        self.Baseline.setTitle(_translate("MainWindow", "Baseline(Min)"))
        self.baseline_start.setText(_translate("MainWindow", "Start:"))
        self.baseline_end.setText(_translate("MainWindow", "End:"))
        self.update_calculation.setText(_translate("MainWindow", "Update Calculations"))
        item = self.result_value.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "A1"))
        item = self.result_value.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "A2"))
        item = self.result_value.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "A3"))
        item = self.result_value.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "A4"))
        item = self.result_value.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "A5"))
        item = self.result_value.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "A6"))
        item = self.result_value.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "A7"))
        item = self.result_value.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "A8"))
        item = self.result_value.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "B1"))
        item = self.result_value.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "B2"))
        item = self.result_value.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "B3"))
        item = self.result_value.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "B4"))
        item = self.result_value.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "B5"))
        item = self.result_value.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "B6"))
        item = self.result_value.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "B7"))
        item = self.result_value.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "B8"))
        item = self.result_value.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ct Value"))
        item = self.result_value.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Std Dev"))
        __sortingEnabled = self.result_value.isSortingEnabled()
        self.result_value.setSortingEnabled(False)
        self.result_value.setSortingEnabled(__sortingEnabled)
        self.File.setTitle(_translate("MainWindow", "File(Csv)"))
        self.file_csv.setText(_translate("MainWindow", "Dir:"))
        self.update_calculation_2.setText(_translate("MainWindow", "Open(Csv)"))
        self.update_calculation_3.setText(_translate("MainWindow", "Save"))
        self.update_calculation_5.setText(_translate("MainWindow", "Capture"))
        self.update_calculation_4.setText(_translate("MainWindow", "Clear"))
        self.Sample.setTitle(_translate("MainWindow", "Samples"))
        self.checkBox_A1.setText(_translate("MainWindow", "A1"))
        self.checkBox_A2.setText(_translate("MainWindow", "A2"))
        self.checkBox_A3.setText(_translate("MainWindow", "A3"))
        self.checkBox_A4.setText(_translate("MainWindow", "A4"))
        self.checkBox_A5.setText(_translate("MainWindow", "A5"))
        self.checkBox_A6.setText(_translate("MainWindow", "A6"))
        self.checkBox_A7.setText(_translate("MainWindow", "A7"))
        self.checkBox_A8.setText(_translate("MainWindow", "A8"))
        self.checkBox_B1.setText(_translate("MainWindow", "B1"))
        self.checkBox_B2.setText(_translate("MainWindow", "B2"))
        self.checkBox_B3.setText(_translate("MainWindow", "B3"))
        self.checkBox_B4.setText(_translate("MainWindow", "B4"))
        self.checkBox_B5.setText(_translate("MainWindow", "B5"))
        self.checkBox_B6.setText(_translate("MainWindow", "B6"))
        self.checkBox_B7.setText(_translate("MainWindow", "B7"))
        self.checkBox_B8.setText(_translate("MainWindow", "B8"))
        self.label_8.setText(_translate("MainWindow", "WinnoZ. V. 1.0.2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

